language: java
jdk:
  - oraclejdk12
before_install:
  - wget https://github.com/jacopofar/italian-nlp-library/releases/download/v0.1/it_verb_model.db
  - ls && mkdir -p target/test-classes && cp -v it_verb_model.db target/test-classes
  - wget https://github.com/jacopofar/italian-nlp-library/releases/download/v0.1/it_POS_model.db
  - cp -v it_POS_model.db target/test-classes
  - wget https://github.com/jacopofar/italian-nlp-library/releases/download/v0.1/it-token.bin
  - ls && mkdir -p target/test-classes && cp -v it-token.bin target/test-classes
  - wget https://github.com/jacopofar/italian-nlp-library/releases/download/v0.1/it-sent.bin
  - cp -v it-sent.bin target/test-classes
  - wget https://github.com/jacopofar/italian-nlp-library/releases/download/v0.1/it-pos-maxent.bin
  - cp -v it-pos-maxent.bin target/test-classes
  - wget https://github.com/jacopofar/italian-nlp-library/releases/download/v0.1/stopwords.txt
  - cp -v stopwords.txt target/test-classes
